# Generated by Django 5.2.17 on 2026-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('WEAPON', 'Weapon'), ('VEHICLE', 'Vehicle'), ('COMMUNICATION', 'Communication'), ('ELECTRONICS', 'Electronics'), ('OTHER', 'Other')], max_length=30)),
                ('base', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('TRANSFERRED', 'Transferred'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
